from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import * 
from PyQt5.QtGui import * 
from PyQt5.QtWidgets import *
from login import login
from main import Ui_MainWindow2
class Ui_MainWindow(Ui_MainWindow2):
    def __init__(self):
        import sys
        self.app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        self.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(self.app.exec_())
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 776)
        MainWindow.setAnimated(True)
        MainWindow.setFixedSize(1029, 776)
        MainWindow.setWindowIcon(QIcon("logo.ico"))
        self.MainWindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 150, 581, 475))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 310, 461, 80))
        self.label.setObjectName("label")
        self.label.hide()
        self.label.setFont(QFont('Times', 15))
        self.label.setStyleSheet("color: red;")
        self.username = QtWidgets.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(70, 170, 301, 61))
        self.username.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.username.setClearButtonEnabled(False)
        self.username.setObjectName("username")
        self.username.setFont(QFont('Times', 15))
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(70, 240, 301, 61))
        self.password.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.password.setFont(QFont('Times', 15))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_b = QtWidgets.QPushButton(self.groupBox)
        self.login_b.setGeometry(QtCore.QRect(290, 390, 211, 51))
        self.login_b.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.login_b.setObjectName("login_b")
        self.login_b.clicked.connect(self.clicked)
        self.login_b.setFont(QFont('Times', 15))
        self.username_label = QtWidgets.QLabel(self.groupBox)
        self.username_label.setEnabled(True)
        self.username_label.setGeometry(QtCore.QRect(390, 180, 221, 51))
        self.username_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.username_label.setObjectName("username_label")
        self.username_label.setFont(QFont('Times', 15))
        self.login_label = QtWidgets.QLabel(self.groupBox)
        self.login_label.setEnabled(True)
        self.login_label.setGeometry(QtCore.QRect(60, 40, 301, 111))
        self.login_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.login_label.setObjectName("login_label")
        self.login_label.setFont(QFont('Times', 15))
        self.password_label = QtWidgets.QLabel(self.groupBox)
        self.password_label.setEnabled(True)
        self.password_label.setGeometry(QtCore.QRect(370, 250, 241, 51))
        self.password_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.password_label.setObjectName("password_label")
        self.password_label.setFont(QFont('Times', 15))
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ارشيف"))
        self.label.setText(_translate("MainWindow", "*اسم المستخدم او كلمة المرور غير صحيحة. "))
        self.login_b.setText(_translate("MainWindow", "تسجيل الدخول"))
        self.username_label.setText(_translate("MainWindow", "اسم المستخدم"))
        self.login_label.setText(_translate("MainWindow", "الرجاء تسجيل الدخول"))
        self.password_label.setText(_translate("MainWindow", "كلمة المرور"))
    def clicked(self):
        user = self.username.text()
        pas = self.password.text()
        succ , user_id , user_prem = login(user,pas)
        if succ :
            self.MainWindow.hide()
            window = Ui_MainWindow2(user_id , user_prem)
            window.show()
        else:
            self.password.clear()
            self.label.show()
if __name__ == "__main__":
    ui = Ui_MainWindow()
